Preliminary zero-IQ port of VQF to Rust
SlimeVR/SlimeVR-Rust pull request #149
Opened 2023-01-19 00:52 UTC by Noxime

Its python. Like, it really is just python. This probably could have even been done with an AI. It's that dumb. Haven't tested it, might not work. Doesn't have the full API either. Straight up sucks

2023-01-19 01:09 UTC, kitlith commented
It would be nice to copy over the docs at some point, but that shouldn't be a blocker for merging and using it in the firmware, only for publishing for other people to use.

2023-01-19 01:22 UTC, TheButlah approved these changes
Awesome work! I would not have had the stomach for it myself. Glad someone did it.

We can use @kitlith's vqf-cxx crate to create some black box tests to compare this to the original implementation. Only once we do that should we think about renaming any of these functions.

2023-01-19 01:22 UTC, TheButlah commented on firmware/crates/vqf/.vscode/settings.json
> +}
this file shouldn't need to exist generally speaking

2023-01-19 01:22 UTC, TheButlah commented on firmware/Cargo.toml
> +members = ["crates/panic_defmt", "crates/defmt_esp_println", "crates/vqf"]
vqf is not platform dependent, so it should not be in the firmware workspace. I would suggest putting it in the main workspace.

The basic strategy here is that as much code as possible is in the toplevel workspace, and only stuff that needs `.cargo/config.toml`, linker flags, and the like, should be in the firmware workspace.

2023-01-19 01:22 UTC, TheButlah commented on firmware/crates/vqf/Cargo.toml
> +license = "MIT"
be  sure to copy the author's original MIT license file and paste it in the root of your crate.

2023-01-19 01:22 UTC, TheButlah commented on firmware/crates/vqf/Cargo.toml
> +version = "0.1.0"
set this version to 0.0.0 for now, until we black box test against vqf-cxx. *then* we can publish to crates.io
```suggestion
version = "0.0.0"
```

2023-01-19 01:22 UTC, TheButlah commented on firmware/crates/vqf/Cargo.toml
> +license = "MIT"
```suggestion
license = "MIT"
publish = false
```

2023-01-19 01:23 UTC, TheButlah requested changes
.

2023-01-20 18:23 UTC, TheButlah commented
build still fails

2023-01-22 21:57 UTC, kitlith reviewed
These two suggested changes should fix CI. This changes from requesting a matrix of any kind to requesting specifically a statically sized matrix, explicitly excluding the possibility of a dynamically sized matrix.

(without alloc, there are no dynamically sized matrices, which is why the complaint only occurs when the std feature is enabled)

2023-01-22 21:57 UTC, kitlith commented on vqf/src/lib.rs
> +		let mut out = nalgebra::Matrix::zeros();
```suggestion
		let mut out = nalgebra::SMatrix::zeros();
```

2023-01-22 21:57 UTC, kitlith commented on vqf/src/lib.rs
> +	let y = b[0] * x + nalgebra::Matrix::repeat(state[0]);
```suggestion
	let y = b[0] * x + nalgebra::SMatrix::repeat(state[0]);
```

2023-01-24 03:40 UTC, TheButlah requested changes
thoughts?

2023-01-24 03:40 UTC, TheButlah commented on vqf/README.md
> +Licensed under the [MIT License](https://spdx.org/licenses/MIT.html)
```suggestion
Licensed under the [MIT License](https://spdx.org/licenses/MIT.html)

All contributors to this crate additionally agree that should the original work be relicensed under a dual MIT/[Apache 2.0](https://spdx.org/licenses/Apache-2.0.html) license, their contributions will also be licensed this way.
```

2023-01-27 06:20 UTC, merged