Clarification on goals and PRs for firmware
SlimeVR/SlimeVR-Rust pull request #166
Opened 2023-01-28 23:20 UTC by TheButlah

CC @ImUrX @Noxime @carl-anders @kitlith

2023-01-28 23:41 UTC, ImUrX requested changes

2023-01-28 23:41 UTC, ImUrX commented on firmware/docs/CONTRIBUTING.md
> +* Read [Goals.md] if you are interested about the project goals.
linking doesn't work

2023-01-28 23:41 UTC, ImUrX commented on firmware/README.md
> +Read [CONTRIBUTING.md]
linking doesnt work

2023-01-29 07:46 UTC, TheButlah commented
Gave it a second pass to make goals simpler.

2023-01-29 08:25 UTC, TheButlah commented on firmware/docs/CONTRIBUTING.md
> +* Read [Goals.md] if you are interested about the project goals.
fixed

2023-01-29 08:26 UTC, TheButlah commented on firmware/README.md
> +Read [CONTRIBUTING.md]
Fixed

2023-01-31 02:28 UTC, TheButlah commented
will merge tomorrow end of day (GMT-5) if no further clarification is needed

2023-01-31 04:22 UTC, ImUrX approved these changes

2023-02-01 07:07 UTC, merged